apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipient-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipient
  template:
    metadata:
      labels:
        app: recipient
    spec:
      containers:
        - name: recipient
          image: paulonova/recipient-service

---
apiVersion: v1
kind: Service
metadata:
  name: recipient-service
spec:
  selector:
    app: recipient
  ports:
    - name: recipient
      protocol: TCP
      port: 3002
      targetPort: 3002