apiVersion: v1
kind: Pod
metadata:
  name: transactions
spec:
  containers:
  - name: transactions-service
    image: paulonova/transactions-service:v0.0.1

---
apiVersion: v1
kind: Service
metadata:
  name: transactions
spec:
  selector:
    app: transactions
  ports:
    - name: transactions
      protocol: TCP
      port: 3001
      targetPort: 3001